version: '3'

services:

  main:
    image: dfranssen/test-websocket
    networks:
      - proxy
      - default
    environment:
      - STOMP_BROKER_RELAY_HOST=chat_broker
    deploy:
      replicas: 5
      update_config:
        parallelism: 1
        delay: 10s
      labels:
        - com.df.notify=true
        - com.df.distribute=true
        - com.df.servicePath=/
        - com.df.serviceDomain=127.0.0.1.xip.io
        - com.df.port=8080
        - com.df.httpsOnly=true
        - com.df.xForwardedProto=true

  broker:
    image: rmohr/activemq:5.14.3-alpine
    networks:
      - default
    deploy:
      replicas: 1

networks:
  default:
    external: false
  proxy:
    external: true
